-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 13:00:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema basica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basica` DEFAULT CHARACTER SET utf8 ;
USE `basica` ;

-- -----------------------------------------------------
-- Table `basica`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`pages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `sous_titre` VARCHAR(255) NULL,
  `texte` TEXT NULL,
  `tri` TINYINT(1) UNSIGNED NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`projets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `texte` TEXT NULL,
  `image` VARCHAR(100) NULL,
  `mise_en_avant` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `clients_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projets_clients1_idx` (`clients_id` ASC),
  CONSTRAINT `fk_projets_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `basica`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `texte` TEXT NULL,
  `image` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `basica`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`projets_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`projets_has_tags` (
  `projets_id` INT UNSIGNED NOT NULL,
  `tags_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`projets_id`, `tags_id`),
  INDEX `fk_projets_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_projets_has_tags_projets_idx` (`projets_id` ASC),
  CONSTRAINT `fk_projets_has_tags_projets`
    FOREIGN KEY (`projets_id`)
    REFERENCES `basica`.`projets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projets_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `basica`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `roles_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `basica`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`auteurs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`posts_has_auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`posts_has_auteurs` (
  `posts_id` INT UNSIGNED NOT NULL,
  `auteurs_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`posts_id`, `auteurs_id`),
  INDEX `fk_posts_has_auteurs_auteurs1_idx` (`auteurs_id` ASC),
  INDEX `fk_posts_has_auteurs_posts1_idx` (`posts_id` ASC),
  CONSTRAINT `fk_posts_has_auteurs_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `basica`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_auteurs_auteurs1`
    FOREIGN KEY (`auteurs_id`)
    REFERENCES `basica`.`auteurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`projets_has_auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`projets_has_auteurs` (
  `projets_id` INT UNSIGNED NOT NULL,
  `auteurs_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`projets_id`, `auteurs_id`),
  INDEX `fk_projets_has_auteurs_auteurs1_idx` (`auteurs_id` ASC),
  INDEX `fk_projets_has_auteurs_projets1_idx` (`projets_id` ASC),
  CONSTRAINT `fk_projets_has_auteurs_projets1`
    FOREIGN KEY (`projets_id`)
    REFERENCES `basica`.`projets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projets_has_auteurs_auteurs1`
    FOREIGN KEY (`auteurs_id`)
    REFERENCES `basica`.`auteurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
